export const dias = ['Día', '01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31'];
export const meses = ['Mes', 'Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dec'];
export const ano = ['Año', '2017','2016','2015','2014','2013','2012','2011','2010','2009','2008','2007','2006','2005','2004','2003','2002','2001','2000','1999','1998','1997','1996','1995','1994','1993','1992','1991','1990','1989','1988','1987','1986','1985','1984','1983','1982','1981','1980','1979','1978','1977','1976','1975','1974','1973','1972','1971','1970','1969','1968','1967','1966','1965','1964','1963','1962','1961','1960'];
export const sexo = ['Masculino', 'Femenino'];
export const nacionalidad = ['Costa Rica'];
export const zona = ['Alajuela', 'Cartago', 'Guanacaste', 'Heredia', 'Limón', 'Puntarenas', 'San José', 'Teletrabajo', 'Extranjero'];
export const civil = ['Soltero', 'Casado', 'Separado', 'Viudo'];
export const giro = ['Selecciona un giro de la empresa', 'Agricultura / Pesca / Ganadería', 'Construcción / Obras', 'Educación', 'Energía', 'Entretenimiento / Deportes', 'Fabricación', 'Finanzas / Banca', 'Gobierno / No Lucro', 'Hostelería / Turismo', 'Informática / Hardware', 'Informática / Software', 'Internet', 'Legal / Asesoría', 'Materias Primas', 'Medios de Comunicación', 'Publicidad / RRPP', 'RRHH / Personal', 'Salud / Medicina', 'Servicios Profesionales', 'Telecomunicaciones', 'Transporte', 'Venta al Consumidor', 'Venta al por mayor', 'Otro'];
export const nivelEstudios = ['Seleccionar el nivel de estudios', 'Secundaria', 'Bachillerato / Preparatoria', 'Técnico Superior', 'Certificación', 'Diplomado / Curso', 'Licenciatura', 'Maestría', 'Doctorado', 'Postgrado'];
export const statusEstudios = ['Selecciona el estado', 'Terminado', 'Aplazado / Trunco', 'Cursando'];
export const idiomas = ['Selecciona un idioma', 'Inglés', 'Afrikaans', 'Albanés', 'Alemán', 'Alsaciano', 'Amárico', 'Árabe', 'Aragonés', 'Armenio', 'Asturiano', 'Aymara', 'Azerí', 'Bajo sajón', 'Bengalí', 'Bielorruso', 'Birmano', 'Bosnio', 'Bretón', 'Búlgaro', 'Canarés', 'Catalán', 'Chamorro', 'Checo', 'Cheroquí', 'Chino mandarín', 'Chino simplificado', 'Chino tradicional', 'Coreano', 'Corso', 'Croata', 'Curdo', 'Danés', 'Eslovaco', 'Esloveno', 'Español', 'Esperanto', 'Estonio', 'Euskera', 'Feroés', 'Filipino', 'Finlandés', 'Fiyiano', 'Francés', 'Frisón', 'Galés', 'Gallego', 'Georgiano', 'Griego', 'Guaraní', 'Gujaratí', 'Hebreo', 'Hindi', 'Holandés', 'Húngaro', 'Ido', 'Igbo', 'Indonesio', 'Irlandés', 'Islandés', 'Italiano', 'Japonés', 'Javanés', 'Kazako', 'Laosiano', 'Latín', 'Letón', 'Lingala', 'Lituano', 'Luxemburgués', 'Macedonio', 'Malabar', 'Malayo', 'Malgache', 'Maltés', 'Manés', 'Maorí', 'Marati', 'Moldavo', 'Mongol', 'Náhuatl', 'Nauruano', 'Noruego', 'Occitano', 'Papiamento', 'Persa', 'Polaco', 'Portugués', 'Punjabí', 'Quechua', 'Quirguiz', 'Romanche', 'Rumano', 'Ruso', 'Sardo', 'Serbio', 'Sesotho', 'Siciliano', 'Somalí', 'Sueco', 'Swahili', 'Tagalo', 'Tailandés', 'Tamil', 'Tártaro', 'Tégulu', 'Tibetano', 'Turco', 'Turcomano', 'Ucraniano', 'Urdu', 'Uzbeko', 'Valón', 'Vietnamita', 'Volapuk', 'Xhosa', 'Yidish', 'Yoruba', 'Zulú'];
export const nivelIdiomas = ['Selecciona el nivel', 'Básico', 'Intermedio', 'Avanzado', 'Nativo'];

export function checkSocialSession() {

}
